### ISSUE TITLE
bug: Latest checkout of git receives data, but doesn't stream to targets

### ISSUE THREAD

**Issue by popey** [wimpysworld/stream-sprout#25]
**I confirm this bug has not already been reported**
- [X] I have searched the issues and this bug has not been reported previously

**Describe the bug**

I checked out the latest code and ran stream-sprout with YouTube and Twitch enabled. I also had the IP set to 0.0.0.0 and also the public IP of the host stream-sprout was running on. It didn't work in either instance. I had it configured with a stream key for the stream-sprout (which I didn't previously).

It accepted the stream data from OBS, but nothing turned up on Twitch or YouTube.

I can test again later to confirm with latest.

**To Reproduce**
1. Grab the latest stream-sprout from the tip of git
2. Configure for two streams - YouTube and Twitch
3. Video arrives at stream-sprout, but never at the end points.
4. Rolling back to v0.1.1 worked

**Expected behavior**

Video to appear in YouTube Studio and Twitch.

**Stream Sprout output**

<details>
  <summary>Stream Sprout output</summary>

Stream Sprout v0.1.4 using ./stream-sprout.yaml
 🌐 rtmp://x.y.z.a:1935
 📡 twitch
 📡 youtube
 ⬇  FFmpeg process (681859) logging to /tmp/stream-sprout.JiLFJJ.log
 ⏸  FFmpeg is standing-by [14:19:18]
 ⏸  FFmpeg is standing-by [14:19:48]
 ⏸  FFmpeg is standing-by [14:20:18]
 👁  FFmpeg detected a new stream
    ├─ Audio: 48000 Hz aac (LC) in Mono ~163 kb/s
    ╰─ Video: 1920x1080 h264 at 60 fps ~6144 kb/s
 ▶  FFmpeg is streaming   [14:20:38]
 ▶  FFmpeg is streaming   [14:20:48]
 ▶  FFmpeg is streaming   [14:21:18]
 ⏹  FFmpeg has stopped

</details>

```text
[rtmp @ 0x55cdd6b4b900] App field don't match up:  <-> rtmp_buffer=0&rtmp_live=live
[rtmp @ 0x55cdd6b4b900] Unexpected stream , expecting x.y.z.a:1935?rtmp_buffer=0&rtmp_live=live
    Last message repeated 1 times
Input #0, flv, from 'rtmp://x.y.z.a:1935?rtmp_buffer=0&rtmp_live=live':
  Metadata:
    fileSize        : 0
    audiochannels   : 1
    2.1             : false
    3.1             : false
    4.0             : false
    4.1             : false
    5.1             : false
    7.1             : false
    encoder         : obs-output module (libobs version 30.2.0)
  Duration: 00:00:00.00, start: 0.032000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp, 163 kb/s
  Stream #0:1: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 6144 kb/s, 60 fps, 60 tbr, 1k tbn
[tee @ 0x55cdd6ba4c00] Input stream #0 is not mapped to any slave.
[tee @ 0x55cdd6ba4c00] Input stream #1 is not mapped to any slave.
Output #0, tee, to '':
  Metadata:
    fileSize        : 0
    audiochannels   : 1
    2.1             : false
    3.1             : false
    4.0             : false
    4.1             : false
    5.1             : false
    7.1             : false
    encoder         : obs-output module (libobs version 30.2.0)
  Duration: 00:00:00.00, start: 0.032000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp, 163 kb/s
  Stream #0:1: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 6144 kb/s, 60 fps, 60 tbr, 1k tbn
[tee @ 0x55cdd6ba4c00] Input stream #0 is not mapped to any slave.
[tee @ 0x55cdd6ba4c00] Input stream #1 is not mapped to any slave.
Output #0, tee, to '':
  Metadata:
    fileSize        : 0
    audiochannels   : 1
    2.1             : false
    3.1             : false
    4.0             : false
    4.1             : false
    5.1             : false
    7.1             : false
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp, 163 kb/s
  Stream #0:1: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 6144 kb/s, 60 fps, 60 tbr, 60 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
rtmp://x.y.z.a:1935?rtmp_buffer=0&rtmp_live=live: Input/output error01x
frame= 2634 fps= 56 q=-1.0 Lsize=N/A time=00:00:48.04 bitrate=N/A speed=1.01x
video:32156kB audio:926kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

**System information**
- OS: Debian GNU/Linux 12 (bookworm)
- stream-sprout version: 0.1.4
- FFmpeg version: 5.1.5-0+deb12u1

**Screenshots**

![image](https://github.com/user-attachments/assets/5cb6acdc-f4aa-4536-9fe1-43da22fb7fd7)

**Additional context**

Love you, mean it. 😻

**Comment by flexiondotorg** [comment]
Thanks for including the log output, that does inform me where the breakage is:

```
Output #0, tee, to '':
```

That :point_up: means none of the destinations are actually populated, so Stream Sprout is not forwarding any data anywhere :facepalm:
